name: Powledge
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_ml_kit: ^0.16.3
  google_mlkit_image_labeling: ^0.10.0
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_face_detection: ^0.9.0
  image_picker: ^1.0.2
  camera: ^0.10.5+3
  path: ^1.8.2
  path_provider: ^2.1.0

  #STATE_MANAGEMENT
  stacked: ^3.4.2
  stacked_services: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner:
  stacked_generator: ^1.3.2


flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/ml/
  - assets/ml/89.png
  - images/Powledge.png
  - images/Powledge2.png

